java -classpath "C:\Program Files\Java\jdk1.8.0_144\jre\lib\charsets.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\deploy.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\access-bridge-64.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\cldrdata.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\dnsns.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\jaccess.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\jfxrt.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\localedata.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\nashorn.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\sunec.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\sunjce_provider.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\sunmscapi.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\sunpkcs11.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\zipfs.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\javaws.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\jce.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\jfr.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\jfxswt.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\jsse.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\management-agent.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\plugin.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\resources.jar;
C:\Program Files\Java\jdk1.8.0_144\jre\lib\rt.jar;
E:\Doktorat\PDTP\pitest-master\pitest-master\SAM-System\target\classes;
E:\Doktorat\PDTP\pitest-master\pitest-master\pitest\target\classes;
C:\Users\Michal\.m2\repository\org\ow2\asm\asm\5.0.4\asm-5.0.4.jar;
C:\Users\Michal\.m2\repository\org\ow2\asm\asm-commons\5.0.4\asm-commons-5.0.4.jar;
C:\Users\Michal\.m2\repository\org\ow2\asm\asm-tree\5.0.4\asm-tree-5.0.4.jar;
C:\Users\Michal\.m2\repository\com\thoughtworks\xstream\xstream\1.4.8\xstream-1.4.8.jar;
C:\Users\Michal\.m2\repository\xmlpull\xmlpull\1.1.3.1\xmlpull-1.1.3.1.jar;
C:\Users\Michal\.m2\repository\xpp3\xpp3_min\1.1.4c\xpp3_min-1.1.4c.jar;
C:\Users\Michal\.m2\repository\junit\junit\4.11\junit-4.11.jar;
C:\Users\Michal\.m2\repository\org\spockframework\spock-core\1.1-groovy-2.4\spock-core-1.1-groovy-2.4.jar;
C:\Users\Michal\.m2\repository\org\codehaus\groovy\groovy-all\2.4.9\groovy-all-2.4.9.jar;
E:\Doktorat\PDTP\pitest-master\pitest-master\pitest-html-report\target\classes;
C:\Users\Michal\.m2\repository\org\antlr\stringtemplate\3.2.1\stringtemplate-3.2.1.jar;
C:\Users\Michal\.m2\repository\antlr\antlr\2.7.7\antlr-2.7.7.jar;
C:\Users\Michal\.m2\repository\net\sf\jopt-simple\jopt-simple\4.9\jopt-simple-4.9.jar;
C:\Users\Michal\.m2\repository\org\assertj\assertj-core\1.6.1\assertj-core-1.6.1.jar" org.pitest.mutationtest.sam.MainWorker